CREATE DATABASE poo;

USE poo; 

DROP TABLE IF EXISTS users; 
CREATE TABLE IF NOT EXISTS users (
id int (11) NOT NULL AUTO_INCREMENT,
name varchar(100) NOT NULL,
age int (3) NOT NULL,
email varchar(100) NOT NULL,
PRIMARY KEY (id)
) ENGINE= MyISAM AUTO_INCREMENT= 0 DEFAULT CHARSET= latin1;